### ISSUE TITLE
Imagenet pretrained

### ISSUE THREAD

**Issue by pribadihcr** [Coderx7/SimpNet#1]
Hi @Coderx7,

Have you train it with Imagenet ?

**Comment by Coderx7** [comment]
@pribadihcr : Hi, no, not yet.
I currently do not have access to any good hardware for training the architecture on ImageNet. When I get my hands on one, and train it, I will update the results and add the pretrained models as well.

**Comment by Coderx7** [comment]
I know its long overdue, but finally after several years, I could manage to get my hands on a somewhat powerful enough gpu that could allow me to at least run some models on imagenet. 
Here is the link to pretrained models : https://github.com/Coderx7/SimpleNet_Pytorch#imagenet-result 
if God wills, I'll be updating a few more variants as well and update this repository as well.
